Implementation/syntax highlight
insper-education/devlife-support-api pull request #40
Opened 2021-11-10 07:19 UTC by cicerotcv

2021-11-19 20:15 UTC, toshikurauchi requested changes
Just a couple of comments, but everything looks good.

In the storybook setting values to `leftTitle`, `rightTitle` and `title` didn't do anything, is that expected?

2021-11-19 20:15 UTC, toshikurauchi commented on frontend/frontend-dev/src/components/CodeVisualizer/index.tsx
> +          color: "##555a7b",
I think there's an extra `#` here

2021-11-19 20:15 UTC, toshikurauchi commented on frontend/frontend-dev/src/fragments/ExerciseResultVisualization/InstructorCodeExerciseResult/index.tsx
> +import { Fragment, useState } from "react";
Do we need to import `Fragment` here?

2021-11-19 20:15 UTC, toshikurauchi commented on frontend/frontend-dev/src/fragments/ExerciseResultVisualization/InstructorCodeExerciseResult/index.tsx
> +                // compare: (
Do we need this comment?

2021-11-20 07:36 UTC, cicerotcv commented
> Just a couple of comments, but everything looks good.
> 
> In the storybook setting values to `leftTitle`, `rightTitle` and `title` didn't do anything, is that expected?

That's right. It's not implemented yet. It will work when the header of the CodeBlock component. I'll fix this PR addressing the comments you've made and removing these props for now.

2021-11-22 14:52 UTC, toshikurauchi commented
> > Just a couple of comments, but everything looks good.
> > In the storybook setting values to `leftTitle`, `rightTitle` and `title` didn't do anything, is that expected?
> 
> That's right. It's not implemented yet. It will work when the header of the CodeBlock component. I'll fix this PR addressing the comments you've made and removing these props for now.

You can keep the props, it's fine. I just wanted to confirm that they were not being used yet. Let me know when you want me to re-review your PR.

2021-11-23 14:06 UTC, toshikurauchi approved these changes

2021-11-23 14:06 UTC, merged