Backend code for Code exercises diff
insper-education/devlife-support-api pull request #55
Opened 2021-11-29 20:02 UTC by igordsm

Fix #50 

Add endpoints 

* `offerings/<int:off_pk>/exercises/<slug:ex_slug>/answers/<int:ans_pk>/students/`
* `offerings/<int:off_pk>/exercises/<slug:ex_slug>/answers/<int:ans_pk>/students/<int:student_pk>`

that return all students that tried an exercise and all answers for a single student. 

@cicerotcv Is there anything else you might need?

2021-11-30 14:09 UTC, toshikurauchi requested changes

2021-12-03 19:36 UTC, igordsm commented on core/tests.py
> +    def test_instructor_lists_all_answers(self):
This is done in test `test_student_lists_their_own_answers`. If a student visits `f'offerings/{self.offering.pk}/exercises/{self.exercise1.slug}/answers'` they only their get own answers. If an instructor visits that URL they get all answers.

2021-12-06 14:24 UTC, toshikurauchi requested changes

2021-12-06 14:24 UTC, toshikurauchi commented on devlife_support/settings.py
> +            "NAME": 'db.sqlite3'
`BASE_DIR` is missing here

2021-12-06 17:02 UTC, merged